language: node_js

node_js:
  - 10.16.3

script:
  - echo "hello"

before_install:
  - openssl aes-256-cbc -K $encrypted_1c7f53a7177c_key -iv $encrypted_1c7f53a7177c_iv -in ./ci/Dashboard-Epitech-b336a22ee4c7.json.enc -out /tmp/Dashboard-Epitech-b336a22ee4c7.json -d

deploy:
  provider: gae
  keyfile: /tmp/Dashboard-Epitech-b336a22ee4c7.json
  project: dashboard-epitech-257222
  config: "./app/app.yaml"
  on:
    branch: master

