language: node_js

node_js:
- 10.16.3

script:
- echo "hello"

before_deploy:
  - openssl aes-256-cbc -K $encrypted_4571f2083710_key -iv $encrypted_4571f2083710_iv -in test-commiteo-2b2dde132075.json.enc -out /tmp/test-commiteo-2b2dde132075.json -d

deploy:
  provider: gae
  keyfile: /tmp/test-commiteo-2b2dde132075.json
  project: dashboard-epitech
  config: "./app/app.yaml"
  on:
    branch: master
