version: "3"

services:
  frontend:
    container_name: frontend-dashboard
    build: 
      context: ./app
      dockerfile: Dockerfile
    environment:
      DEV_ENV: "TRUE"
    image: frontend-dashboard
    ports:
      - 80:3000
    volumes:
      - "./app:/app"

  users_api:
    container_name: users_api
    build: 
      context: ./api/users
      dockerfile: Dockerfile
    environment:
      DEV_ENV: "TRUE"
      PORT: "9000"
    image: users_api_dashboard
    links:
      - db:database
    depends_on:
      - db
    ports:
      - 9000:9000

  widget_api:
    container_name: widget_api
    build: 
      context: ./api/widget
      dockerfile: Dockerfile
    environment:
      DEV_ENV: "TRUE"
      PORT: "9001"
    image: widget_api_dashboard
    links:
      - db:database
    depends_on:
      - db
    ports:
      - 9001:9001

  news_api:
    container_name: news_api
    build: 
      context: ./api/news
      dockerfile: Dockerfile
    environment:
      DEV_ENV: "TRUE"
    image: news_api_dashboard
    volumes:
      - "./api/news:/app"
    ports:
      - 9002:5000
  
  db:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - db:db
    depends_on:
      - db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - /sessions

volumes:
  db-data: