version: "3"

services:
  app:
    container_name: app
    build: 
      context: ./app
      dockerfile: Dockerfile
    environment:
      DEV_ENV: "TRUE"
    image: app-test-dashboard
    ports:
      - 80:8080