runtime: go

api_version: go1

service: intra

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
  - url: .*
    script: _go_app
    secure: always
    redirect_http_response_code: 301