runtime: custom

env: flex

service: default

manual_scaling:
  instances: 2
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

handlers:
  - url: .*
    script: auto
    secure: always
    redirect_http_response_code: 301
