runtime: nodejs10

env: flex

service: default

manual_scaling:
  instances: 4
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

handlers:
  - url: .*
    script: auto
    secure: always
    redirect_http_response_code: 301