version: "3"

services:
  db:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./volumes/mysql/:/var/lib/mysql

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links: 
        - db:db
      ports:
        - 80:80
      environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: test
      volumes:
        - /sessions