runtime: python37

entrypoint: gunicorn -b :$PORT main:app

service: news

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
  - url: .*
    script: auto
    secure: always
    redirect_http_response_code: 301